apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: UGwxMjM0NTY=   # you can change password other base64 format words
  MYSQL_PASSWORD: Q2xhcnVzd2F5XzE=    # you can change password other base64 format words
