apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: mysql-storage
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /export/nfs-share 
    server: 192.168.142.200